"""Add initial_balance for users

Revision ID: 1bf44139651b
Revises: bbd7a5867f79
Create Date: 2026-03-12 16:33:30.528881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf44139651b'
down_revision = 'bbd7a5867f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_balance', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('initial_balance')

    # ### end Alembic commands ###
