"""add last_real_balance to users

Revision ID: 35398a4daec4
Revises: 1bf44139651b
Create Date: 2026-03-13 19:47:09.054024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35398a4daec4'
down_revision = '1bf44139651b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_real_balance', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_real_balance')

    # ### end Alembic commands ###
