"""rename file_url to file_key

Revision ID: b0d6f6f4d31f
Revises: cbbffa520cbe
Create Date: 2026-08-02 12:57:04.429700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d6f6f4d31f'
down_revision = 'cbbffa520cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_key', sa.String(length=512), nullable=True))
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.drop_column('file_key')

    # ### end Alembic commands ###
