server {
    listen 80;

    # 1. Frontend
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
    }

    # 2. API (Flask)
    location /api/v1/ {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}