server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # 1. Роздаємо фронтенд
    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }

    # 2. Перенаправляємо API запити на бекенд (Python)
    location /api/ {
        # 'backend' - це ім'я сервісу з docker-compose, порт 5000
        proxy_pass http://backend:5000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    error_page 404 /index.html;

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}