"""Add mono_id to Transactions

Revision ID: c947b72a47b9
Revises: fa945992d6bf
Create Date: 2025-11-02 23:37:58.504832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c947b72a47b9'
down_revision = 'fa945992d6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mono_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['mono_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('mono_id')

    # ### end Alembic commands ###
