"""Add monobank api

Revision ID: fa945992d6bf
Revises: 140e5aff2723
Create Date: 2025-11-02 15:19:37.767861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa945992d6bf'
down_revision = '140e5aff2723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monobank_api_token', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['monobank_api_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('monobank_api_token')

    # ### end Alembic commands ###
