"""Add icon for categories

Revision ID: 4b2b4ca36c31
Revises: 821b2b0877cb
Create Date: 2025-12-22 22:17:44.349111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2b4ca36c31'
down_revision = '821b2b0877cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=False, server_default='bi-tag-fill'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
