"""Monobank api token from str to bytes

Revision ID: 5ce8796d1f93
Revises: aece7b7001f6
Create Date: 2025-11-05 19:05:38.427719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce8796d1f93'
down_revision = 'aece7b7001f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('monobank_api_token',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=True,
               postgresql_using='monobank_api_token::bytea')

        batch_op.drop_constraint(batch_op.f('users_monobank_api_token_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_monobank_api_token_key'), ['monobank_api_token'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('monobank_api_token',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
