"""Fix unique constants for mono_ids

Revision ID: 5fa7f4becec1
Revises: a82fbff3ec7a
Create Date: 2026-01-19 11:33:13.088969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa7f4becec1'
down_revision = 'a82fbff3ec7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transactions_mono_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_user_mono_tx', ['user_id', 'mono_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_mono_tx', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('transactions_mono_id_key'), ['mono_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
