"""Add refresh_token to users

Revision ID: a82fbff3ec7a
Revises: 4b2b4ca36c31
Create Date: 2026-01-03 21:57:51.064969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82fbff3ec7a'
down_revision = '4b2b4ca36c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_refresh_token'), ['refresh_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_refresh_token'))
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###
