"""Add mcc_code to Category

Revision ID: aece7b7001f6
Revises: c947b72a47b9
Create Date: 2025-11-03 18:45:01.780579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aece7b7001f6'
down_revision = 'c947b72a47b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mcc_code', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('mcc_code')

    # ### end Alembic commands ###
